service: ${env:SERVICE_NAME}

frameworkVersion: '>=1.0.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:REGION}
  environment: ${file(config/environment.yml)}

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  secrets: /${self:service}/${env:STAGE}
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'

functions: ${file(config/functions.yml)}
